# Generated by Django 6.1.1 on 2026-09-20 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('academic_role', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('preferred_communication_method', models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('research_interests', models.TextField(blank=True)),
                ('orcid', models.CharField(blank=True, help_text='Format: 0000-0000-0000-0000', max_length=19)),
                ('website', models.URLField(blank=True)),
                ('preferred_citation_style', models.CharField(blank=True, choices=[('APA', 'APA'), ('MLA', 'MLA'), ('CHICAGO', 'Chicago'), ('HARVARD', 'Harvard'), ('VANCOUVER', 'Vancouver'), ('IEEE', 'IEEE'), ('OTHER', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client profile',
                'verbose_name_plural': 'client profiles',
            },
        ),
        migrations.CreateModel(
            name='EditorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_name', models.CharField(blank=True, max_length=255)),
                ('professional_title', models.CharField(blank=True, max_length=255)),
                ('biography', models.TextField(blank=True)),
                ('academic_background', models.TextField(blank=True)),
                ('professional_experience', models.TextField(blank=True)),
                ('subject_areas', models.TextField(blank=True, help_text='Comma-separated for now; becomes a structured relation in Phase 9.')),
                ('editing_specializations', models.TextField(blank=True)),
                ('citation_styles', models.TextField(blank=True, help_text='Comma-separated citation styles the editor is comfortable with.')),
                ('years_of_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, max_length=255)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LIMITED', 'Limited availability'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive editors are excluded from assignment matching.')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='editor_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'editor profile',
                'verbose_name_plural': 'editor profiles',
            },
        ),
    ]
