# Generated by Django 6.1.1 on 2026-09-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic Editing'), ('SCIENTIFIC', 'Scientific Editing')], max_length=20)),
                ('pricing_model', models.CharField(choices=[('PER_WORD', 'Per word'), ('PER_PAGE', 'Per page'), ('PER_HOUR', 'Per hour'), ('FLAT_FEE', 'Flat fee'), ('CUSTOM', 'Custom quote')], max_length=20)),
                ('minimum_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'subject area',
                'verbose_name_plural': 'subject areas',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
