# Generated by Django 6.1.1 on 2026-09-23 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, editable=False, help_text='Auto-generated, e.g. UETC-2026-0012.', max_length=32, unique=True)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('client_declared_word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('system_calculated_word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('billable_word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('citation_style', models.CharField(blank=True, max_length=100)),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('journal_guidelines', models.TextField(blank=True)),
                ('requested_deadline', models.DateField()),
                ('confirmed_deadline', models.DateField(blank=True, null=True)),
                ('client_instructions', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Staff-only. Never rendered on any client-facing view.')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('KRW', 'South Korean Won'), ('CNY', 'Chinese Yuan'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal')], default='KES', max_length=3)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('QUOTE_PENDING', 'Quote Pending'), ('QUOTE_SENT', 'Quote Sent'), ('QUOTE_ACCEPTED', 'Quote Accepted'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAID', 'Paid'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('QUALITY_REVIEW', 'Quality Review'), ('AWAITING_CLIENT', 'Awaiting Client'), ('REVISION_REQUESTED', 'Revision Requested'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined'), ('DISPUTED', 'Disputed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_as_editor', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_as_client', to=settings.AUTH_USER_MODEL)),
                ('senior_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_as_senior_editor', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='website.service')),
                ('subject_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='website.subjectarea')),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
